# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site Setup
title: Devyunsy 개발 블로그
# It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: Android, iOS 개발자의 블로그입니다
baseurl: "/blog"
paginate: 5

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty


# About/contact
author:
  name: Seungyong Yun
  url: http://devyunsy88.github.io
  email: yo0230@gmail.com
  github: http://github.com/devyunsy88
  about: https://branded.me/seungyongyun

version: 0.1.0


gems:
  - jekyll-paginate
